### ISSUE TITLE
Add Kitsu login

### ISSUE THREAD

**Issue by matthewdias** [matthewdias/Kitsu.bundle#1]
login gives us
- nsfw access
- title preferences

**Comment by sachaw** [comment]
any chance of integrating the scrobber into the metadata agent, because once you implement login support then you can just make library update calls on the fly.

**Comment by matthewdias** [comment]
Im not sure. I need to investigate whether it's possible to have a plug-in run in agent mode and daemon mode.

**Comment by sachaw** [comment]
good ref if you find it's possible https://github.com/trakt/Plex-Trakt-Scrobbler

**Comment by matthewdias** [comment]
After switching to daemon mode agent functionality still works. I'll start trying to integrate the scrobbler alongside login.

**Comment by sachaw** [comment]
that would be amazing, also may solve multi user support issue as well.

**Comment by matthewdias** [comment]
will certainly make it easier yeah

**Comment by matthewdias** [comment]
After playing around with it I think its much more trouble than its worth to try to do the scrobbler in plugin. Needs a lot of workarounds to fight against Plex. Because of that, and the fact that Plex [isn't supporting plugins](https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/) anymore, I think ill just leave them separate.

**Comment by sachaw** [comment]
dam, but understandable, hope they open up the platform a little in the future.

**Comment by matthewdias** [comment]
Implemented in https://github.com/matthewdias/Kitsu.bundle/commit/f6d273045dd3fa6f987957477e65bd2986c1e394
