### ISSUE TITLE
Agent fails when supplied with incorrect credentials

### ISSUE THREAD

**Issue by sachaw** [matthewdias/Kitsu.bundle#3]
Changed my kitsu password the other day, and:
Edit (Too long):
https://pastebin.com/MFpsqJwE

**Comment by matthewdias** [comment]
Ah, need to invalidate token on failure. Thanks for the report.

**Comment by matthewdias** [comment]
oh yeah in the meantime you can delete the bad token in `$PLEX_HOME/Plug-in Support/Data`

**Comment by matthewdias** [comment]
Due to plex limitations there's not a good user-facing way to invalidate tokens. Tried to make this as easy as possible. Your options are:
1. Dig into the filesystem and delete it manually per my previous comment
2. Do it through the plex interface
	- remove your kitsu login info from the agent settings
	- attempt a metadata refresh on a show
	- token should now be deleted and you can login again
